[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.4.1"
edition = "2024"

[workspace.dependencies]
mcad-geom = { version = "0.4.1", path = "crates/mcad-geom" }
mcad-core = { version = "0.4.1", path = "crates/mcad-core" }
mcad-io = { version = "0.4.1", path = "crates/mcad-io" }
