[package]
name = "mcad-io"
version.workspace = true
edition.workspace = true

[dependencies]
dxf = "0.6.1"
mcad-core = { version = "0.1.0", path = "../mcad-core" }
mcad-geom = { version = "0.1.0", path = "../mcad-geom" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"
